### ISSUE TITLE
sshlatex does depend on bash as login shell

### ISSUE THREAD

**Issue by sternenseemann** [iblech/sshlatex#1]
Possible Fix: Call bash prior to the other ssh commands.

**Comment by iblech** [comment]
Thanks for the report! I'll look into it. I'm scared of quoting issues though. :-)

**Comment by iblech** [comment]
Do you know a way for ssh to execute a given command (e.g. `["/bin/bash", "-c", "..."]`) without passing a string as `/bin/bash -c ...` to the remote host's default shell?

**Comment by iblech** [comment]
Judging from https://github.com/openssh/openssh-portable/blob/master/session.c#L1870, it seems that there isn't a way to do that. Quoting hell it is, then.

**Comment by sternenseemann** [comment]
This is sad unfortunate since this means that one always has to make assumptions about the shell. :\

**Comment by iblech** [comment]
Turns out it isn't that bad. One can use the following idiom:

```
ssh foo.example.org "$(cat <<'EOF'
    bash -c '
        # ... bash source code here ...
        # Single quotes have to be written in the following way: '\''
    '
EOF
)"
```

sshlatex should now work with any shell which interprets the command `bash -c '...'` in the way one thinks it should. Thanks again for raising this issue. :-)

**Comment by sternenseemann** [comment]
Nice, thank you!
